//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Momatov.ClassFolder.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityControl
    {
        public int ID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> DetailID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string GOST { get; set; }
    
        public virtual Detail Detail { get; set; }
        public virtual Item Item { get; set; }
        public virtual Product Product { get; set; }
        public virtual Region Region { get; set; }
    }
}
