//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Momatov.ClassFolder.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterial
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeRawMaterialID { get; set; }
        public int Count { get; set; }
        public int Guarantee { get; set; }
        public int UnitOfMeasurementID { get; set; }
        public decimal UnitCost { get; set; }
    
        public virtual TypeRawMaterial TypeRawMaterial { get; set; }
        public virtual UnitOfMeasurement UnitOfMeasurement { get; set; }
    }
}
