//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Momatov.ClassFolder.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realization
    {
        public int ID { get; set; }
        public int Volume { get; set; }
        public System.DateTime RealizationDate { get; set; }
        public int ProductTypeID { get; set; }
        public int ReleaseNumber { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual ProductType ProductType { get; set; }
    }
}
