//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Momatov.ClassFolder.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkshopEquipment
    {
        public Nullable<int> WorkshopID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public int Count { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Workshop Workshop { get; set; }
    }
}
